#ifndef PHP_5_6_18_DARUMA_FUNCTIONS_H
#define PHP_5_6_18_DARUMA_FUNCTIONS_H

#include "library.h"

#define RET_ERRO_ZEND_BIND
#define ZEND_PARAM		INTERNAL_FUNCTION_PARAMETERS
#define ZEND_PARAM_PASS INTERNAL_FUNCTION_PARAM_PASSTHRU

#endif //PHP_5_6_18_DARUMA_FUNCTIONS_H
