#!/bin/bash

echo "Este aplicativo preparara sua maquina para operaçao com a impressora Daruma"
echo "pressione <Enter> para prosseguir ou CTRL + C para cancelar"
read
sleep 2

export http_proxy=http://192.168.111.25:3128 

echo "Atualizando Para a última versão do php5"

apt-get update
apt-get -q -y install php5-dev

if [ -d /tmp/libdaruma ]; then
	rm -rf /usr/local/share/DarumaFramework
	rm -rf /tmp/libdaruma
fi
 
mkdir -p /usr/local/share/DarumaFramework
 
chmod -R 777 /usr/local/share/DarumaFramework
 
echo "Baixando bibliotecas da Daruma"

mkdir /tmp/libdaruma
 
cd /tmp/libdaruma

PHP_VERSION=`php -v 2> /dev/null | egrep ^PHP | cut -d ' ' -f 2 | cut -d '-' -f 1`

wget --no-cache http://terminal.moveissimonetti.com.br/desenvolvimento/MS-TEF/$PHP_VERSION/DarumaFramework.zip

if [ $? != 0 ]; then
    echo "Erro no download do pacote. Tente novamente"
    exit 1
fi

unzip -x DarumaFramework.zip
 
if [ -d /opt/DarumaFramework ]; then
	rm -rf /opt/DarumaFramework
fi
 
mkdir -p /opt/DarumaFramework
 
cp DarumaFramework/* /opt/DarumaFramework/
 
chmod -R 777 /opt/DarumaFramework
 
cp php_darumaframework.ini /etc/php5/mods-available/

VERSION_ZEND_MODULE=`phpize -v 2> /dev/null | egrep ^Zend\ Module | cut -d ' ' -f 10`

if [ ! -d /usr/lib/php5/$VERSION_ZEND_MODULE ]; then
	mkdir /usr/lib/php5/$VERSION_ZEND_MODULE	
fi

cp php_darumaframework.so /usr/lib/php5/$VERSION_ZEND_MODULE/
 
php5enmod php_darumaframework
 
service apache2 restart 

